title: emma-cookbook Docs
description: Technical documentation for emma-cookbook.
theme: just-the-docs

url: "https://dennislent.github.io"
baseurl: "/cookbook"

color_scheme: light
search_enabled: true
heading_anchors: true

aux_links:
  GitHub Repository:
    - "https://github.com/DennisLent/cookbook"
