# Generated by hand for additional optional recipe fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipe_cook_time_recipe_prep_time_recipe_servings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="origin",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="recipe",
            name="source_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="recipe",
            name="source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="author_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cuisine",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="recipe",
            name="course",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(blank=True, choices=[("easy", "easy"), ("medium", "medium"), ("hard", "hard")], max_length=20),
        ),
        migrations.AddField(
            model_name="recipe",
            name="calories",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="nutrition",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="recipe",
            name="equipment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="video_url",
            field=models.URLField(blank=True),
        ),
    ]

