# Generated by hand to add Favorite model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_recipe_more_optional_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="favorites", to="users.user")),
                ("recipe", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="favorites", to="recipes.recipe")),
            ],
            options={
                "unique_together": {("user", "recipe")},
            },
        ),
    ]

