# Generated by hand to add role and customization fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(choices=[("admin", "admin"), ("user", "user")], default="user", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="layout",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="widget_whitelist",
            field=models.JSONField(blank=True, default=list),
        ),
    ]

