# Generated by Django 6.0.3 on 2026-03-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_customizations_and_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_recipe_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
