# Generated by Django 6.0.3 on 2026-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_display_name_user_favorite_recipe_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUpdateStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_version", models.CharField(blank=True, max_length=64)),
                ("latest_version", models.CharField(blank=True, max_length=64)),
                ("repository", models.CharField(blank=True, max_length=255)),
                ("release_url", models.URLField(blank=True)),
                ("update_available", models.BooleanField(default=False)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("dismissed_version", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App update status",
                "verbose_name_plural": "App update status",
            },
        ),
    ]
